yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

TEXT_ELEMENTS = 15
User = get_user_model()


class Group(models.Model):
    title = models.CharField('Название группы', max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField('Описание группы')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
        indexes = [
            models.Index(fields=['slug'], name='unique_group'),
        ]


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Вы можете оставить комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария',
    )
    text = models.TextField('Текст комментария')
    created = models.DateTimeField('Дата публикации', auto_now_add=True)

    class Meta:
        ordering = ['-created']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор публикаций',
    )

    class Meta:
        ordering = ['-author']
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_subscription')
        ]


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:TEXT_ELEMENTS]

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

yatube/posts/forms.py
from django import forms
from django.forms import Textarea
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Текст поста',
            'group': 'Группа',
        }
        help_texts = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост'
        }
        widgets = {
            'name': Textarea(attrs={'cols': 80, 'rows': 20})
        }
        error_messages = {
            'text': {
                'required': 'Заполните поле'
            },
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        widgets = {
            'text': Textarea(attrs={'cols': 1, 'rows': 5})
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.decorators.cache import cache_page
from .models import Post, Group, Follow
from .forms import PostForm, CommentForm
from .paginator import pagination


User = get_user_model()


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = Post.objects.select_related('author', 'group')
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_obj = pagination(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = author.following
    if request.user.is_authenticated or not following.exists():
        is_following = False
    else:
        is_following = following.filter(user=request.user).exists()
    posts = author.posts.select_related('group')
    post_count = posts.count()
    page_obj = pagination(request, posts)
    context = {
        'author': author,
        'is_following': is_following,
        'page_obj': page_obj,
        'post_count': post_count,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    this_post = get_object_or_404(Post, pk=post_id)
    posts = this_post.author.posts.all()
    post_count = posts.count()
    form = CommentForm()
    comments = this_post.comments.all()
    context = {
        'post': this_post,
        'post_count': post_count,
        'form': form,
        'comments': comments
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user.username)
    context = {
        'form': form
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    this_post = get_object_or_404(Post, pk=post_id)
    if this_post.author == request.user:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=this_post
        )
        if form.is_valid():
            post = form.save(False)
            post.author = request.user
            post.save()
            return redirect('posts:post_detail', post_id=post_id)
        context = {
            'this_post': this_post,
            'form': form,
            'is_edit': True,
        }
        return render(request, 'posts/create_post.html', context)
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = pagination(request, posts)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:follow_index')


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:follow_index')

yatube/templates/posts/create_post.html
{% extends 'base.html' %} 
{% block title %}
Новый пост 
{% endblock %}
{% block content %}
<div class='row justify-content-left'>
    <div class='col-md-8 p-5'>
      <div class='card'>
        <div class='card-header'>
            {% if is_edit %}
              Редактировать пост
            {% else %}
                Добавить пост
            {% endif %}
        </div>
          <div class='card-body'>
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class='alert alert-danger'>
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class='alert alert-danger'>
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}
              {% if is_edit %}
                <form method='post' enctype="multipart/form-data" action='{% url 'posts:post_edit' this_post.id %}'>
              {% else %}
                <form method='post' enctype="multipart/form-data" action='{% url 'posts:post_create' %}'>
              {% endif %} 
              {% csrf_token %}
              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class='form-group row my-3'>
                  <label for='{{ field.id_for_label }}'>
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class='required text-danger'>*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id='{{ field.id_for_label }}-help'
                         class='form-text text-muted'
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class='d-flex justify-content-start'>
                <button type='submit' class='btn btn-primary'>
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                         
                </button> 
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %}
  Ваши подписки
{% endblock %}

{% block content %}
  <div class='container py-5'>     
  <h1>Ваши подписки</h1>
  {% include 'includes/switcher.html' %}
  {% for post in page_obj %}
  <article>
    <ul>
      <li>
      Автор: {{ post.author.get_full_name }}
      </li>
      <li>
      Дата публикации: {{ post.pub_date|date:'d E Y' }}
      </li>
    </ul>      
    <p>
    {{ post.text }}
    </p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    {% if post.group %}
      <a href='{% url 'posts:group_list' post.group.slug %}'>все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  </article>
  {% endfor %}
  {% include 'includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %} 
{% block title %}
  {{ group.title }}
{% endblock %}

{% block content %}
<div class='container py-5'>
  <h1> {{ group.title }}</h1>
  <p>
    {{ group.description }}
  </p>
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}     
</div>  
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %} 
{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <div class='container py-5'>     
  <h1>Последние обновления на сайте</h1>
  {% include 'includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'includes/article.html' %}
    {% if post.group %}
      <a href='{% url 'posts:group_list' post.group.slug %}'>все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'includes/paginator.html' %}
  </div>  
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %} 
{% load thumbnail %}
{% block title %}
Пост {{ post.text|truncatewords:30 }}
{% endblock %}

{% block content %}
  <div class='row'>
    <aside class='col-12 col-md-3'>
      <ul class='list-group list-group-flush'>
        <li class='list-group-item'>
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        {% if post.group %}   
        <li class='list-group-item'>
          Группа: {{ post.group }}<br>
          <a href='{% url 'posts:group_list' post.group.slug %}'>
            все записи группы
          </a>
        </li>
        {% endif %}
        <li class='list-group-item'>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class='list-group-item d-flex justify-content-between align-items-center'>
          Всего постов автора:  <span >{{ post_count }}</span>
        </li>
        <li class='list-group-item'>
          <a href='{% url 'posts:profile' post.author.username %}'>
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>
    {% thumbnail post.image '960x339' crop='center' upscale=True as im %}
      <img class='card-img my-2' src='{{ im.url }}'>
    {% endthumbnail %}
    <article class='col-12 col-md-9'>
      <p>
        {{ post.text }} 
      </p>
      {% include 'includes/comment.html' %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %} 
{% block title %}
  Профайл пользователя {{ author }} 
{% endblock %}

{% block content %}
  <div class='container py-5'>
    <div class="mb-5">   
      <h1>Все посты пользователя {{ author }} </h1>
      <h3>Всего постов: {{ post_count }} </h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
      {% endif %}
    </div>
  {% for post in page_obj %}  
    {% include 'includes/article.html' %}
    <a href='{% url 'posts:post_detail' post.pk %}'>подробная информация</a>
    {% if post.group %} <br>
    <a href='{% url 'posts:group_list' post.group.slug %}'>все записи группы</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'includes/paginator.html' %}
  </div> 
{% endblock %}